### ISSUE TITLE
"Aguardando dados de stream" infinito

### ISSUE THREAD

**Issue by murilommelo** [m4sterin/crp-iframe-player#2]
Depois que o site da Crunchyroll atualizou, fica no "Aguardando dados de stream" infinitamente

Assim não possibilitando a visualização de nenhum vídeo

Teria como vocês resolverem e enviarem a atualização pra cá?😃

**Comment by m4sterin** [comment]
Tá atualizado, só baixar novamente a atualizar a sua pasta.

Lembrnado que a nova versão do site (Crunchyroll Beta)  não tem trailers nos eps premium, ou seja, a extensão é compatível, porém é >completamente dependente< do site do Crunchyroll Antigo.

se por acaso o beta substituir o site antigo, a extensão vai permanentemente parar de funcionar =/
